# Generated by Django 5.0.2 on 2024-03-02 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EventCalendar', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attendee',
        ),
    ]
