# Generated by Django 5.0.2 on 2024-03-02 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventCalendar', '0002_delete_attendee'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_desc',
            field=models.CharField(default='Event description, lorem ipsum dolor sit amet consectetur adipisicing elit.', max_length=300, verbose_name='event description'),
        ),
        migrations.AddField(
            model_name='event',
            name='event_guest_count',
            field=models.IntegerField(default='0', verbose_name='event guest count'),
        ),
        migrations.AddField(
            model_name='event',
            name='event_img_url',
            field=models.URLField(default='https://picsum.photos/500/300', verbose_name='event image url'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_name',
            field=models.CharField(max_length=75, verbose_name='event name'),
        ),
    ]
